---
name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run linkcheck and summarise results
        uses: ./
        with:
          python-version: "3.11"
          requirements-file: docs/requirements.txt
          sphinx-directory: docs
